# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_manager:
  ros__parameters:
    arm_group_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - base_waist_joint
        - waist_arm_joint
        - arm_end_joint